// THIS FILE IS AUTOGENERATED
#pragma once

#include <lngs/lngs.hpp>

// clang-format off
namespace lngs::app {
    enum class lng {
        /// usage:  (Synopsis header; please note there is one space at the end of this entry)
        ARGS_USAGE = 500,
        /// <arg> (Default name of an argument)
        ARGS_DEF_META = 501,
        /// positional arguments (Header for list of positional arguments)
        ARGS_POSITIONALS = 502,
        /// optional arguments (Header for list of optional arguments)
        ARGS_OPTIONALS = 503,
        /// shows this help message and exits (Description for the -h/--help argument)
        ARGS_HELP_DESCRIPTION = 504,
        /// unrecognized argument: {0} (Error message for an unrecognized argument; the placeholder will contain the name of the argument)
        ARGS_UNRECOGNIZED = 505,
        /// argument {0}: expected one argument (Error message for a missing argument)
        ARGS_NEEDS_PARAM = 506,
        /// argument {0}: value was not expected (Error message for unneeded value)
        ARGS_NEEDS_NO_PARAM = 1039,
        /// argument {0}: expected a number (Error message for a numeric argument, when parsing failed)
        ARGS_NEEDS_NUMBER = 507,
        /// argument {0}: number outside of expected bounds (Error message for a numeric argument, when parsing would get outside of representable bounds)
        ARGS_NEEDED_NUMBER_EXCEEDED = 508,
        /// argument {0}: value {1} is not recognized (Error message for a list of arguments, when parsing failed)
        ARGS_NEEDS_ENUM_UNKNOWN = 1040,
        /// known values for {0}: {1} (Help message presenting a list of possible values for a list-type argument)
        ARGS_NEEDS_ENUM_KNOWN_VALUES = 1041,
        /// argument {0} is required (Error message for a missing required argument)
        ARGS_REQUIRED = 509,
        /// {0}: error: {1} (Error message template; placeholder 0 will get the name of program, placeholder 1 an actual message)
        ARGS_ERROR_MSG = 510,
        /// Translates PO/MO file to LNG file. (Help description for the 'lngs make' command)
        ARGS_APP_DESCR_CMD_MAKE = 511,
        /// Creates POT file from message file. (Help description for the 'lngs pot' command)
        ARGS_APP_DESCR_CMD_POT = 512,
        /// Creates header file from message file. (Help description for the 'lngs enums' command)
        ARGS_APP_DESCR_CMD_ENUMS = 513,
        /// Creates Python module with string keys. (Help description for the 'lngs py' command)
        ARGS_APP_DESCR_CMD_PY = 514,
        /// Creates C++ file with fallback resource for the message file. (Help description for the 'lngs res' command)
        ARGS_APP_DESCR_CMD_RES = 515,
        /// Reads the language description file and assigns values to new strings. (Help description for the 'lngs freeze' command)
        ARGS_APP_DESCR_CMD_FREEZE = 516,
        /// [-h] [--version] [--share <dir>] <command> [<arguments>] (Synopsis for the app. The "[-h] [--version] [--share" part should be left intact, only the "<dir>", "command" and "arguments" words should be translated.)
        ARGS_APP_DESCR_USAGE = 517,
        /// The flow for string management and creation (Title for the description of the flow for different roles)
        ARGS_APP_FLOW_TITLE = 518,
        /// Translation Manager (Name of a role responsible for finalizing the list of translations)
        ARGS_APP_FLOW_ROLE_STRMGR = 519,
        /// Translator (Name of a role responsible for supplying translated strings)
        ARGS_APP_FLOW_ROLE_TRANSLATOR = 520,
        /// Developer (compiling existing list) (Name of a role responsible for updating the C++ interfaces to project-specific lngs files)
        ARGS_APP_FLOW_ROLE_DEV_COMPILE = 521,
        /// Developer (adding new string) (Name of a role responsible for adding new entries to be used in the code)
        ARGS_APP_FLOW_ROLE_DEV_ADD = 522,
        /// Developer (releasing a build) (Name of a role responsible for transforming .po files to lngs files)
        ARGS_APP_FLOW_ROLE_DEV_RELEASE = 523,
        /// known commands (Header for list of known commands)
        ARGS_APP_KNOWN_CMDS = 524,
        /// command missing (Error message displayed, when a command is missing in the command line)
        ARGS_APP_NO_COMMAND = 525,
        /// unknown command: {0} (Error message displayed, when a command from command line is not recognized)
        ARGS_APP_UNK_COMMAND = 526,
        /// <when> (Name of argument holding always/never/auto value)
        ARGS_APP_META_WHEN = 1042,
        /// <file> (Name of argument holding a file name)
        ARGS_APP_META_FILE = 527,
        /// <holder> (Name of argument for rights holder)
        ARGS_APP_META_HOLDER = 528,
        /// <email> (Name of argument holding an email address)
        ARGS_APP_META_EMAIL = 529,
        /// <title> (Name of argument holding a heading)
        ARGS_APP_META_TITLE = 530,
        /// <gettext file> (Name of argument holding a file name for a GetText PO/MO file)
        ARGS_APP_META_PO_MO_FILE = 531,
        /// <dir> (Name of argument holding a directory)
        ARGS_APP_META_DIR = 1032,
        /// shows program version and exits (Description for 'version' argument)
        ARGS_APP_VERSION = 532,
        /// uses color in diagnostics; <when> is 'never', 'always', or 'auto' (Description for 'color' argument; <when> should translated the same, as ARGS_APP_META_WHEN, words 'never', 'always', and 'auto' should be left unchanged)
        ARGS_APP_COLOR = 1043,
        /// replaces {0} as new data directory (Description for 'share' argument)
        ARGS_APP_SHARE_REDIR = 1033,
        /// shows more info (Description for 'verbose' argument)
        ARGS_APP_VERBOSE = 533,
        /// sets the name of copyright holder (Description for 'copyright' argument)
        ARGS_APP_COPYRIGHT = 534,
        /// sets the name and email address of first author (Description for 'author' argument)
        ARGS_APP_AUTHOR = 535,
        /// sets a descriptive title for the POT project (Description for 'title' argument)
        ARGS_APP_TITLE = 536,
        /// instructs the Strings type to use data generated by the `lngs res'. (Description for 'resource' argument)
        ARGS_APP_RESOURCE = 537,
        /// replaces missing strings with warped ones; resulting strings are always singular (Description for argument adding in English strings of missing entries, but replacing all letters with similar-looking but different letters.)
        ARGS_APP_WARP_MISSING_SINGULAR = 538,
        /// replaces all strings with warped ones; plural strings will still be plural (as if English) (Description for argument changing all strings in a resource file, by replacing all letters with similar-looking but different letters.)
        ARGS_APP_WARP_ALL_PLURAL = 539,
        /// adds block of strings with key names (Description for argument allowing for additional, optional block in resulting file)
        ARGS_APP_WITH_KEY_BLOCK = 540,
        /// sets file name to #include in the implementation of the Resource class; defaults to "<project>.hpp". (Description for argument allowing to change the name of an include file to be more in-line with project's layout)
        ARGS_APP_ALT_INCLUDE = 541,
        /// sets POT file name to write results to; use "-" for standard output (Description for output argument for lngs pot)
        ARGS_APP_OUT_POT = 542,
        /// sets C++ header file name to write results to; use "-" for standard output (Description for output argument for lngs enums)
        ARGS_APP_OUT_CPP = 543,
        /// sets C++ code file name with builtin strings to write results to; use "-" for standard output (Description for output argument for lngs res)
        ARGS_APP_OUT_RES = 544,
        /// sets Python file name to write results to; use "-" for standard output (Description for output argument for lngs py)
        ARGS_APP_OUT_PY = 545,
        /// sets LNG binary file name to write results to; use "-" for standard output (Description for output argument for lngs make)
        ARGS_APP_OUT_LNG = 546,
        /// sets IDL message file name to write results to; it may be the same as input; use "-" for standard output (Description for output argument for lngs freeze)
        ARGS_APP_OUT_IDL = 547,
        /// sets message file name to read from (Description for input argument taking IDL file)
        ARGS_APP_IN_IDL = 548,
        /// sets GetText message file name to read from (Description for input argument taking GetText PO/MO file)
        ARGS_APP_IN_PO_MO = 549,
        /// sets ATTR_LANGUAGE file name with ll_CC (language_COUNTRY) names list (Description for input argument taking TXT file with language/country names)
        ARGS_APP_IN_LLCC = 550,
        /// note (Name of the severity label for notes.)
        SEVERITY_NOTE = 1001,
        /// warning (Name of the severity label for warnings.)
        SEVERITY_WARNING = 1002,
        /// error (Name of the severity label for errors.)
        SEVERITY_ERROR = 1003,
        /// fatal (Name of the severity label for fatals.)
        SEVERITY_FATAL = 1004,
        /// could not open `{0}' (Needed file was not found; filename is going to be shown as argument {0}.)
        ERR_FILE_MISSING = 1005,
        /// could not open the file (Needed file was not found; filename is going to be shown as source of message.)
        ERR_FILE_NOT_FOUND = 1006,
        /// `{0}' is not strings file (Presented as additional message, if input file was not parsed properly.)
        ERR_NOT_STRINGS_FILE = 1007,
        /// no new strings (Shown by lngs freeze.)
        ERR_NO_NEW_STRINGS = 1008,
        /// attribute `{0}' should not be empty (Used for attributes with no value. The argument represents the name of the attribute.)
        ERR_ATTR_EMPTY = 1009,
        /// attribute `{0}' is missing (Optional attribute is not present. The argument represents the name of the attribute.)
        ERR_ATTR_MISSING = 1010,
        /// required attribute `{0}' is missing (A required attribute is not present. The argument represents the name of the attribute.)
        ERR_REQ_ATTR_MISSING = 1011,
        /// before finalizing a value, use `id(-1)' (Hint for IDL authors, when an id attribute is missing.)
        ERR_ID_MISSING_HINT = 1012,
        /// expected {0}, got {1} (Information about bad syntax in the strings file. The arguments represent the expected and actual token, respectively.)
        ERR_EXPECTED = 1013,
        /// unrecognized text (Used as second argument for ERR_EXPECTED, as in "..., got unrecognized text")
        ERR_EXPECTED_GOT_UNRECOGNIZED = 1014,
        /// end of file (Used as first argument for ERR_EXPECTED, as in "expected EOF")
        ERR_EXPECTED_EOF = 1034,
        /// end of line (Used as first argument for ERR_EXPECTED, as in "expected EOL")
        ERR_EXPECTED_EOL = 1035,
        /// string (Used as first argument for ERR_EXPECTED, as in "expected string")
        ERR_EXPECTED_STRING = 1016,
        /// number (Used as first argument for ERR_EXPECTED, as in "expected number")
        ERR_EXPECTED_NUMBER = 1017,
        /// identifier (Used as first argument for ERR_EXPECTED, as in "expected identifier")
        ERR_EXPECTED_ID = 1018,
        /// end of file (Used as second argument for ERR_EXPECTED, as in "..., got EOF")
        ERR_EXPECTED_GOT_EOF = 1019,
        /// end of line (Used as second argument for ERR_EXPECTED, as in "..., got EOL")
        ERR_EXPECTED_GOT_EOL = 1036,
        /// string (Used as second argument for ERR_EXPECTED, as in "..., got string")
        ERR_EXPECTED_GOT_STRING = 1020,
        /// number (Used as second argument for ERR_EXPECTED, as in "..., got number")
        ERR_EXPECTED_GOT_NUMBER = 1021,
        /// identifier (Used as second argument for ERR_EXPECTED, as in "..., got identifier")
        ERR_EXPECTED_GOT_ID = 1022,
        /// message file does not contain translation for "{0}" (Warning for a missing string. The argument will be replaced by identifier with missing translation.)
        ERR_MSGS_TRANSLATION_MISSING = 1023,
        /// message file does not contain Language attribute (The gettext MO file has no attribute for language-REGION pair. The word "Language" is not to be translated.)
        ERR_MSGS_ATTR_LANG_MISSING = 1024,
        /// locale {0} has no name (Message for missing name for a locale with no name for the culture in file with locale/name pairs.)
        ERR_UNANMED_LOCALE = 1025,
        /// no {0} locale on the list (Message for missing locale in file with locale/culture name pairs.)
        ERR_LOCALE_MISSING = 1026,
        /// gettext file format error (The MO file has unexpected contents)
        ERR_GETTEXT_FORMAT = 1027,
        /// two or more blocks occupy the same space (Detail of what was wrong with the contents)
        ERR_GETTEXT_BLOCKS_OVERLAP = 1028,
        /// string not contained inside the block (Detail of what was wrong with the contents)
        ERR_GETTEXT_STRING_OUTSIDE = 1029,
        /// file truncated; data missing (Detail of what was wrong with the contents)
        ERR_GETTEXT_FILE_TRUNCATED = 1030,
        /// strings must end with a zero (Detail of what was wrong with the contents)
        ERR_GETTEXT_NOT_ASCIIZ = 1031,
        /// unrecognized field `{0}' (The PO file has unexpected field name)
        ERR_GETTEXT_UNRECOGNIZED_FIELD = 1037,
        /// unrecognized escape sequence `\{0}' (The PO file has unexpected string contents)
        ERR_GETTEXT_UNRECOGNIZED_ESCAPE = 1038,
    }; // enum class lng

    struct Resource {
        static const char* data();
        static std::size_t size();
    };

    using Strings = lngs::SingularStrings<lng, lngs::VersionedFile<7,
        lngs::storage::FileWithBuiltin<Resource>>>;
} // namespace lngs::app
// clang-format on
