#include <gtest/gtest.h>
#include "diag_helper.h"
#include <lngs/commands.hpp>
#include <lngs/strings.hpp>

namespace lngs::testing {
	using namespace ::std::literals;
	using ::testing::TestWithParam;
	using ::testing::ValuesIn;

	struct enums_result {
		std::string_view input;
		std::string output;
		std::string output_with_res;
	};

	class enums : public TestWithParam<enums_result> {};

	TEST_P(enums, text) {
		auto[input, expected, with_resource] = GetParam();

		diagnostics diag;
		diag.set_contents("", input);

		idl_strings strings;
		bool idl_valid = read_strings(diag.source(""), strings, diag);
		EXPECT_TRUE(idl_valid);

		{
			outstrstream output;
			lngs::enums::write(output, strings, false);
			EXPECT_EQ(expected, output.contents);
		}

		{
			outstrstream output;
			lngs::enums::write(output, strings, true);
			EXPECT_EQ(with_resource, output.contents);
		}
	}

	const enums_result sources[] = {
		{
			R"([serial(0)]
strings {
	[id(-1), help("help string"), plural("values")] ID = "value";
	[id(1001), plural("values"), help("help string")] ID2 = "value2";
	[id(-1), help("help string")] ID3 = "value3";
})",
			R"(// THIS FILE IS AUTOGENERATED
#pragma once

#include <locale/locale.hpp>

namespace  {
    enum class lng {
        ID3 = 1003, // value3 (help string)
    }; // enum class lng

    enum class lngs {
        ID = 1002, // value | values (help string)
        ID2 = 1001, // value2 | values (help string)
    }; // enum class lngs

    using Strings = locale::StringsWithPlurals<lng, lngs>;
}; // namespace 
)",
			R"(// THIS FILE IS AUTOGENERATED
#pragma once

#include <locale/locale.hpp>

namespace  {
    enum class lng {
        ID3 = 1003, // value3 (help string)
    }; // enum class lng

    enum class lngs {
        ID = 1002, // value | values (help string)
        ID2 = 1001, // value2 | values (help string)
    }; // enum class lngs

    struct Resource {
        static const char* data();
        static std::size_t size();
    };

    using Strings = locale::StringsWithPlurals<lng, lngs, locale::storage::FileWithBuiltin<Resource>>;
}; // namespace 
)"
		},
		{
			R"([serial(0), project("name")]
strings {
	[id(-1), help("help string"), plural("values")] ID = "value";
	[id(1001), plural("values"), help("help string")] ID2 = "value2";
	[id(-1), help("help string")] ID3 = "value3";
})",
			R"(// THIS FILE IS AUTOGENERATED
#pragma once

#include <locale/locale.hpp>

namespace name {
    enum class lng {
        ID3 = 1003, // value3 (help string)
    }; // enum class lng

    enum class lngs {
        ID = 1002, // value | values (help string)
        ID2 = 1001, // value2 | values (help string)
    }; // enum class lngs

    using Strings = locale::StringsWithPlurals<lng, lngs>;
}; // namespace name
)",
			R"(// THIS FILE IS AUTOGENERATED
#pragma once

#include <locale/locale.hpp>

namespace name {
    enum class lng {
        ID3 = 1003, // value3 (help string)
    }; // enum class lng

    enum class lngs {
        ID = 1002, // value | values (help string)
        ID2 = 1001, // value2 | values (help string)
    }; // enum class lngs

    struct Resource {
        static const char* data();
        static std::size_t size();
    };

    using Strings = locale::StringsWithPlurals<lng, lngs, locale::storage::FileWithBuiltin<Resource>>;
}; // namespace name
)"
		},
		{
			R"([serial(0), project("name")]
strings {
	[id(1001), help("help string")] ID = "value";
	[id(1002), help("help string")] ID2 = "value2";
	[id(1003), help("help string")] ID3 = "value3";
})",
			R"(// THIS FILE IS AUTOGENERATED
#pragma once

#include <locale/locale.hpp>

namespace name {
    enum class lng {
        ID = 1001, // value (help string)
        ID2 = 1002, // value2 (help string)
        ID3 = 1003, // value3 (help string)
    }; // enum class lng

    using Strings = locale::SingularStrings<lng>;
}; // namespace name
)",
			R"(// THIS FILE IS AUTOGENERATED
#pragma once

#include <locale/locale.hpp>

namespace name {
    enum class lng {
        ID = 1001, // value (help string)
        ID2 = 1002, // value2 (help string)
        ID3 = 1003, // value3 (help string)
    }; // enum class lng

    struct Resource {
        static const char* data();
        static std::size_t size();
    };

    using Strings = locale::SingularStrings<lng, locale::storage::FileWithBuiltin<Resource>>;
}; // namespace name
)"
		},
		{
			R"([serial(0), project("name")]
strings {
	[id(-1), help("help string"), plural("values")] ID = "value";
	[id(1001), plural("values"), help("help string")] ID2 = "value2";
})",
			R"(// THIS FILE IS AUTOGENERATED
#pragma once

#include <locale/locale.hpp>

namespace name {
    enum class lngs {
        ID = 1002, // value | values (help string)
        ID2 = 1001, // value2 | values (help string)
    }; // enum class lngs

    using Strings = locale::PluralOnlyStrings<lngs>;
}; // namespace name
)",
			R"(// THIS FILE IS AUTOGENERATED
#pragma once

#include <locale/locale.hpp>

namespace name {
    enum class lngs {
        ID = 1002, // value | values (help string)
        ID2 = 1001, // value2 | values (help string)
    }; // enum class lngs

    struct Resource {
        static const char* data();
        static std::size_t size();
    };

    using Strings = locale::PluralOnlyStrings<lngs, locale::storage::FileWithBuiltin<Resource>>;
}; // namespace name
)"
		},
		{
			R"([serial(0), project("name")] strings {})",
			R"(// THIS FILE IS AUTOGENERATED
#pragma once

#include <locale/locale.hpp>

namespace name {
    enum class faulty {
        UNDEFINED = 0 // File did not define any string
    }; // enum class faulty

    using Strings = locale::SingularStrings<faulty>;
}; // namespace name
)",
			R"(// THIS FILE IS AUTOGENERATED
#pragma once

#include <locale/locale.hpp>

namespace name {
    enum class faulty {
        UNDEFINED = 0 // File did not define any string
    }; // enum class faulty

    struct Resource {
        static const char* data();
        static std::size_t size();
    };

    using Strings = locale::SingularStrings<faulty, locale::storage::FileWithBuiltin<Resource>>;
}; // namespace name
)"
		},
		{
			R"([serial(0), project("name::sub")] strings {})",
			R"(// THIS FILE IS AUTOGENERATED
#pragma once

#include <locale/locale.hpp>

namespace name::sub {
    enum class faulty {
        UNDEFINED = 0 // File did not define any string
    }; // enum class faulty

    using Strings = locale::SingularStrings<faulty>;
}; // namespace name::sub
)",
			R"(// THIS FILE IS AUTOGENERATED
#pragma once

#include <locale/locale.hpp>

namespace name::sub {
    enum class faulty {
        UNDEFINED = 0 // File did not define any string
    }; // enum class faulty

    struct Resource {
        static const char* data();
        static std::size_t size();
    };

    using Strings = locale::SingularStrings<faulty, locale::storage::FileWithBuiltin<Resource>>;
}; // namespace name::sub
)"
		},
	};

	INSTANTIATE_TEST_CASE_P(sources, enums, ValuesIn(sources));
}
