[
	project("lngs"),
	version("0.3"),
	serial(4)
] strings {
	[help("Name of the severity label for notes."), id(1001)]
	SEVERITY_NOTE = "note";
	[help("Name of the severity label for warnings."), id(1002)]
	SEVERITY_WARNING = "warning";
	[help("Name of the severity label for errors."), id(1003)]
	SEVERITY_ERROR = "error";
	[help("Name of the severity label for fatals."), id(1004)]
	SEVERITY_FATAL = "fatal";

	[help("Needed file was not found; filename is going to be shown as argument {0}."), id(1005)]
	ERR_FILE_MISSING = "could not open `{0}'";
	[help("Needed file was not found; filename is going to be shown as source of message."), id(1006)]
	ERR_FILE_NOT_FOUND = "could not open the file";
	[help("Presented as additional message, if input file was not parsed properly."), id(1007)]
	ERR_NOT_STRINGS_FILE = "`{0}' is not strings file";
	[help("Shown by lngs freeze."), id(1008)]
	ERR_NO_NEW_STRINGS = "no new strings";

	[help("Used for attributes with no value. The argument represents the name of the attribute."), id(1009)]
	ERR_ATTR_EMPTY = "attribute `{0}' should not be empty";
	[help("Optional attribute is not present. The argument represents the name of the attribute."), id(1010)]
	ERR_ATTR_MISSING = "attribute `{0}' is missing";
	[help("A required attribute is not present. The argument represents the name of the attribute."), id(1011)]
	ERR_REQ_ATTR_MISSING = "required attribute `{0}' is missing";
	[help("Hint for IDL authors, when an id attribute is missing."), id(1012)]
	ERR_ID_MISSING_HINT = "before finalizing a value, use `id(-1)'";

	[help("Information about bad syntax in the strings file. The arguments represent the expected and actual token, respectively."), id(1013)]
	ERR_EXPECTED = "expected {0}, got {1}";
	[help("Used as second argument for ERR_EXPECTED, as in \"..., got unrecognized text\""), id(1014)]
	ERR_EXPECTED_GOT_UNRECOGNIZED = "unrecognized text";
	[help("Used as first argument for ERR_EXPECTED, as in \"expected string\""), id(1016)]
	ERR_EXPECTED_STRING = "string";
	[help("Used as first argument for ERR_EXPECTED, as in \"expected number\""), id(1017)]
	ERR_EXPECTED_NUMBER = "number";
	[help("Used as first argument for ERR_EXPECTED, as in \"expected identifier\""), id(1018)]
	ERR_EXPECTED_ID = "identifier";
	[help("Used as second argument for ERR_EXPECTED, as in \"..., got EOF\""), id(1019)]
	ERR_EXPECTED_GOT_EOF = "EOF";
	[help("Used as second argument for ERR_EXPECTED, as in \"..., got string\""), id(1020)]
	ERR_EXPECTED_GOT_STRING = "string";
	[help("Used as second argument for ERR_EXPECTED, as in \"..., got number\""), id(1021)]
	ERR_EXPECTED_GOT_NUMBER = "number";
	[help("Used as second argument for ERR_EXPECTED, as in \"..., got identifier\""), id(1022)]
	ERR_EXPECTED_GOT_ID = "identifier";

	[help("Warning for a missing string. The argument will be replaced by identifier with missing translation."), id(1023)]
	ERR_MSGS_TRANSLATION_MISSING = "message file does not contain translation for \"{0}\"";
	[help("The gettext MO file has no attribute for language-REGION pair. The word \"Language\" is not to be translated."), id(1024)]
	ERR_MSGS_ATTR_LANG_MISSING = "message file does not contain Language attribute";
	[help("Message for missing name for a locale with no name for the culture in file with locale/name pairs."), id(1025)]
	ERR_UNANMED_LOCALE = "locale {0} has no name";
	[help("Message for missing locale in file with locale/culture name pairs."), id(1026)]
	ERR_LOCALE_MISSING = "no {0} locale on the list";

	[help("The MO file has unexpected contents"), id(1027)]
	ERR_GETTEXT_FORMAT = "gettext file format error";
	[help("Detail of what was wrong with the contents"), id(1028)]
	ERR_GETTEXT_BLOCKS_OVERLAP = "two or more blocks occupy the same space";
	[help("Detail of what was wrong with the contents"), id(1029)]
	ERR_GETTEXT_STRING_OUTSIDE = "string not contained inside the block";
	[help("Detail of what was wrong with the contents"), id(1030)]
	ERR_GETTEXT_FILE_TRUNCATED = "file truncated; data missing";
	[help("Detail of what was wrong with the contents"), id(1031)]
	ERR_GETTEXT_NOT_ASCIIZ = "strings must end with a zero";
}
