/*
 * Copyright (C) 2015 midnightBITS
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <lngs/internals/commands.hpp>
#include <lngs/internals/streams.hpp>
#include <lngs/internals/strings.hpp>

namespace lngs::app::py {
	int write(outstream& out, const idl_strings& defs) {
		out.fmt(R"(#!/usr/bin/python
# -*- coding: UTF-8 -*-

# THIS FILE IS AUTOGENERATED

)");
		bool has_singular = false;
		bool has_plural = false;

		for (auto& str : defs.strings) {
			if (!str.plural.empty()) {
				has_plural = true;
				continue;
			}

			has_singular = true;

			auto message = straighten(str.value);
			auto help = straighten(str.help);

			out.fmt("{0} = {1} # {2}", str.key, str.id, message);
			if (!help.empty()) out.fmt(" ({})", help.c_str());
			out.fmt("\n");
		}

		if (has_singular && has_plural) out.fmt("\n");

		for (auto& str : defs.strings) {
			if (str.plural.empty()) continue;

			auto message = straighten(str.value);
			auto plural = straighten(str.plural);
			auto help = straighten(str.help);

			out.fmt("{0} = {1} # {2}", str.key, str.id, message);
			if (!plural.empty()) out.fmt(" | {}", plural.c_str());
			if (!help.empty()) out.fmt(" ({})", help.c_str());
			out.fmt("\n");
		}

		return 0;
	}
}  // namespace lngs::app::py
