// THIS FILE IS AUTOGENERATED
#pragma once

#include <locale/locale.hpp>

namespace lngs {
    enum class lng {
        SEVERITY_NOTE = 1001, // note (Name of the severity label for notes.)
        SEVERITY_WARNING = 1002, // warning (Name of the severity label for warnings.)
        SEVERITY_ERROR = 1003, // error (Name of the severity label for errors.)
        SEVERITY_FATAL = 1004, // fatal (Name of the severity label for fatals.)
    }; // enum class lng

    struct Resource {
        static const char* data();
        static std::size_t size();
    };

    using Strings = locale::SingularStrings<lng, locale::storage::FileWithBuiltin<Resource>>;
}; // namespace lngs
